[package]
name = "subtitle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#Logging
log = "0.4.17"

#Web
warp = "0.3.2"